# Site Settings
title: The Indie Wolf
email: therealindependentwolf@gmail.com
description: >
baseurl: "/theindependentwolf"
url: "http://localhost:4000"
twitter_username: trasol7
github_username:  theindependentwolf
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM