# Site Settings
title: The Independent Wolf
email: therealindependentwolf@gmail.com
description: >
baseurl: "/theindependentwolf"
url: "http://theindependentwolf.com"
twitter_username: trasol7
github_username:  theindependentwolf
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM